// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "GoImageZip/internal/domain"
import mock "github.com/stretchr/testify/mock"

// ImageRepository is an autogenerated mock type for the ImageRepository type
type ImageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ImageRepository) Create(_a0 domain.ImageInfo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ImageInfo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: _a0
func (_m *ImageRepository) GetById(_a0 string) (domain.ImageInfo, error) {
	ret := _m.Called(_a0)

	var r0 domain.ImageInfo
	if rf, ok := ret.Get(0).(func(string) domain.ImageInfo); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.ImageInfo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields:
func (_m *ImageRepository) GetHistory() ([]domain.ImageInfo, error) {
	ret := _m.Called()

	var r0 []domain.ImageInfo
	if rf, ok := ret.Get(0).(func() []domain.ImageInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ImageInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *ImageRepository) Update(_a0 domain.ImageInfo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ImageInfo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
